const db = require("./connection");
const { User, Category, Identity, Ambitions } = require("../models");

db.once("open", async () => {
    await Ambitions.deleteMany();
    await Category.deleteMany();
    await Identity.deleteMany();

    const ambitions = await Ambitions.create({
        category: "Lose Weight",
        dailyPlan: "Weighing myself every morning, exercise six days per week, strict diet for weight loss.",
        endValue: 69.0,
        identity: "Determined",
        public: false,
        events: [
          {createdAt: "June 15, 2022",
          dataInput: 96.0,
          notes: "Starting date."},
          {createdAt: "June 16, 2022",
          dataInput: 94.3,
          notes: ""},
          {createdAt: "June 17, 2022",
          dataInput: 93.1,
          notes: ""},
          {createdAt: "June 18, 2022",
          dataInput: 92.5,
          notes: ""},
          {createdAt: "June 19, 2022",
          dataInput: 92.0,
          notes: ""},
          {createdAt: "June 20, 2022",
          dataInput: 92.0,
          notes: ""},
          {createdAt: "June 21, 2022",
          dataInput: 91.5,
          notes: ""},
          {createdAt: "June 22, 2022",
          dataInput: 91.0,
          notes: ""},
          {createdAt: "June 23, 2022",
          dataInput: 90.4,
          notes: ""},
          {createdAt: "June 24, 2022",
          dataInput: 90.2,
          notes: ""},
          {createdAt: "June 25, 2022",
          dataInput: 89.5,
          notes: ""},
          {createdAt: "June 26, 2022",
          dataInput: 89.2,
          notes: ""},
          {createdAt: "June 27, 2022",
          dataInput: 88.8,
          notes: ""},
          {createdAt: "June 28, 2022",
          dataInput: 88.4,
          notes: ""},
          {createdAt: "June 29, 2022",
          dataInput: 88.1,
          notes: ""},
          {createdAt: "June 30, 2022",
          dataInput: 88.1,
          notes: ""},
          {createdAt: "July 1, 2022",
          dataInput: 87.6,
          notes: ""},
          {createdAt: "July 2, 2022",
          dataInput: 87.3,
          notes: ""},
          {createdAt: "July 3, 2022",
          dataInput: 86.9,
          notes: ""},
          {createdAt: "July 4, 2022",
          dataInput: 87.1,
          notes: ""},
          {createdAt: "July 5, 2022",
          dataInput: 86.7,
          notes: ""},
          {createdAt: "July 6, 2022",
          dataInput: 86.0,
          notes: ""},
          {createdAt: "July 7, 2022",
          dataInput: 85.7,
          notes: ""},
          {createdAt: "July 8, 2022",
          dataInput: 85.2,
          notes: ""},
          {createdAt: "July 9, 2022",
          dataInput: 85.2,
          notes: ""},
          {createdAt: "July 10, 2022",
          dataInput: 84.8,
          notes: ""},
          {createdAt: "July 11, 2022",
          dataInput: 84.8,
          notes: ""},
          {createdAt: "July 12, 2022",
          dataInput: 84.3,
          notes: ""},
          {createdAt: "July 13, 2022",
          dataInput: 84.8,
          notes: "Ate chips and chocolate, caused weight gain."},
          {createdAt: "July 14, 2022",
          dataInput: 84.8,
          notes: ""},
          {createdAt: "July 15, 2022",
          dataInput: 84.8,
          notes: ""},
          {createdAt: "July 16, 2022",
          dataInput: 84.4,
          notes: ""},
          {createdAt: "July 17, 2022",
          dataInput: 83.8,
          notes: ""},
          {createdAt: "July 18, 2022",
          dataInput: 83.7,
          notes: ""},
          {createdAt: "July 19, 2022",
          dataInput: 83.1,
          notes: ""},
          {createdAt: "July 20, 2022",
          dataInput: 82.3,
          notes: ""},
          {createdAt: "July 21, 2022",
          dataInput: 82.4,
          notes: ""},
          {createdAt: "July 22, 2022",
          dataInput: 82.0,
          notes: ""},
          {createdAt: "July 23, 2022",
          dataInput: 82.7,
          notes: "Ate too much Korean fried chicken."},
          {createdAt: "July 24, 2022",
          dataInput: 82.2,
          notes: ""},
          {createdAt: "July 25, 2022",
          dataInput: 82.0,
          notes: ""},
          {createdAt: "July 26, 2022",
          dataInput: 80.8,
          notes: ""},
          {createdAt: "July 27, 2022",
          dataInput: 80.5,
          notes: ""},
          {createdAt: "July 28, 2022",
          dataInput: 80.3,
          notes: ""},
          {createdAt: "July 29, 2022",
          dataInput: 80.1,
          notes: ""},
          {createdAt: "July 30, 2022",
          dataInput: 80.6,
          notes: "Ate 400g of chicken, caused weight gain."},
          {createdAt: "July 31, 2022",
          dataInput: 82.2,
          notes: "Ate too much food not related to my diet, caused weight gain."},
          {createdAt: "August 1, 2022",
          dataInput: 81.4,
          notes: "Ate 400g of chicken, caused weight gain."},
        ]
    });

    const categories = await Category.insertMany([
        { ambitionCategories: "Lose Weight" },
        { ambitionCategories: "Save Money" },
        { ambitionCategories: "New Profession" },
        { ambitionCategories: "New Hobby"},
        { ambitionCategories: "???"}
    ]);
    
    console.log('Categories seeded');

    const identities = await Identity.insertMany([
        { identityCategories: 'Determined' }, 
        { identityCategories: 'Inspired' },
        { identityCategories: 'Motivated' },
        { identityCategories: 'Bored' },
        { identityCategories: '???'},
    ]);
    
    console.log("Identities seeded");

    await User.deleteMany();

    const jack = await User.create({
        username: "r134x7",
        email: 'jack@admin.com',
        password: 'password12345',
        ambitions: [
          {_id: ambitions._id}
        ]
      });

      const jill = await User.create({
        username: "jill",
        email: 'jill@admin.com',
        password: 'password12345',
      });

    console.log('Users seeded');

    process.exit();
});